live_config_reload = true
[env]
TERM = "xterm-256color"
[font]
size = 14.0

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Medium"


[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"
mode = "~Alt"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"
mode = "~Alt"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
action = "ScrollToTop"
mode = "~Alt"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
action = "ScrollToBottom"
mode = "~Alt"
