" Include bundle
source ~/.vim/bundle.vim

" Automatically detect file types.
set nocompatible
filetype plugin indent on

" Load settings
source ~/.vim/settings.vim

" Load functions
source ~/.vim/functions.vim

" Load mappings
source ~/.vim/mappings.vim

" Load auto commands
source ~/.vim/autocmd.vim

" Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
" HatTip: http://robots.thoughtbot.com/faster-grepping-in-vim and
" @ethanmuller
let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

" ag is fast enough that CtrlP doesn't need to cache
let g:ctrlp_use_caching = 0

set rtp+=~/.fzf

if has("gui_running")
  syntax on
  set hlsearch
  colorscheme twilight
  set ai
  set ruler
endif
