# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="amuse"
ZSH_THEME="blinks"

eval "$(hub alias -s)"
fpath=('/usr/local/share/zsh/site-functions' $fpath)

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git brew capistrano coffee colorize composer emoji-clock gem npm node rake ruby rvm svn vundle safe-paste)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH="/usr/local/share/python:/Users/patrick/bin:/usr/local/bin:/usr/local/mysql/bin:/Users/patrick/.rvm/gems/ruby-2.0.0-p247/bin:/Users/patrick/.rvm/gems/ruby-2.0.0-p247@global/bin:/Users/patrick/.rvm/rubies/ruby-2.0.0-p247/bin:/Users/patrick/.rvm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/patrick/sh"
# export MANPATH="/usr/local/man:$MANPATH"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
else
  export EDITOR='vim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

source $HOME/dotfiles/bash/functions
source $HOME/dotfiles/bash/aliases

export TERM=xterm-256color

#export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
# export PATH="$(brew --prefix homebrew/php/php53)/bin:$PATH"
export CONTENTFUL_API_KEY=fee5514f378e237238beb8005413cf55d00f7200e3b2caeb4d44723b123d354b
export PATH="$PATH:$HOME/.composer/vendor/bin/" # Add composer vendor to PATH

fpath=(~/zsh-completions/src $fpath)
autoload -Uz compinit && compinit
# Base16 Shell
# BASE16_SHELL="$HOME/.config/base16-shell/base16-default.dark.sh"
# [[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
#

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

envfile="${HOME}/.gpg-agent-info"

export GPG_TTY=$(tty)

export GPG_AGENT_INFO  # the env file does not contain the export statement
export GPG_AGENT=/usr/local/bin/gpg-agent

export PATH="/usr/local/opt/mysql@5.6/bin:$PATH"
export PATH="$HOME/.npm-packages/bin:$PATH"
export PATH="node_modules/.bin:$PATH"
#source /Users/patrick/.rvm/scripts/rvm

#source ~/.rvm/scripts/rvm

function devauth() {
  pwd=$(pwd)
  cd /Users/patrick/github/crown/ui-dev
  npm run auth
  cd $pwd
}

function devurl() {
  branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
  folder=${PWD##*/}
  if [[ $folder == *-ui ]]; then
      folder=${folder:0:-3}
  fi
  url=https://my.zone1.development.crown.com/$folder/$branch/
  echo The development url for this branch and repository is:
  echo $url
  echo
  echo $url | pbcopy
  echo It has been copied to your clipboard and ready for pasting!
}

export PATH="$HOME/.bin:$PATH"
export PATH=$PATH:$HOME/Library/Python/2.7/bin
export PATH=$PATH:~/bin
export PATH=$PATH:/usr/local/bin
GRAPHVIZ_DOT=/usr/local/bin/dot

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH=$PATH:$HOME/Library/Python/2.7/bin

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/patrick/projects/micro-blog/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/patrick/projects/micro-blog/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/patrick/projects/micro-blog/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/patrick/projects/micro-blog/node_modules/tabtab/.completions/sls.zsh
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[[ -f /Users/patrick/projects/micro-blog/node_modules/tabtab/.completions/slss.zsh ]] && . /Users/patrick/projects/micro-blog/node_modules/tabtab/.completions/slss.zsh
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

eval "$(rbenv init -)"
export PATH=/usr/local/opt/imagemagick@6/bin:$PATH
export PKG_CONFIG_PATH=/usr/local/opt/imagemagick@6/lib/pkgconfig:$PKG_CONFIG_PATH

export PATH="/usr/local/opt/mysql-client/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/mysql-client/lib"
export CPPFLAGS="-I/usr/local/opt/mysql-client/include"
export PKG_CONFIG_PATH="/usr/local/opt/mysql-client/lib/pkgconfig:$PKG_CONFIG_PATH"
